### PR TITLE
Added PrismJS, but it won't work with Contentful Rich Text

### PR DESCRIPTION
**Pull request by mihirgupta0900**
I have successfully added PrismJS to the website. But there is an issue, contentful rich test editor does not specify the language of the code as mentioned [here.](https://www.reddit.com/r/gatsbyjs/comments/evuhvg/contentful_prismjs/fg2zldz?utm_source=share&utm_medium=web2x&context=3) You can resolve this by using the mardown editor from contentful. Nevertheless, I haven't made any changes apart from adding prismjs.

### CODE REVIEW

**Comment by Ckbhatia** [comment]
Hi @mihirgupta0900, Can you please create another branch from master and apply these changes in that branch?

It will be helpful to test your code.

**Comment by mihirgupta0900** [comment]
Sure, let me make the changes.

**Comment by mihirgupta0900** [comment]
Hey, I had a doubt, branch in your main repository or the forked one? I don't have push access to your repo. You can pull the code from the forked repo and check changes there. Or if there are better methods, please let me know.

**Comment by Ckbhatia** [comment]
Hi,

You can do this on your fork. I will download your fork and run it.

Thanks

**Comment by mihirgupta0900** [comment]
My updates are on the master branch of my fork, please check it.

**Comment by Ckbhatia** [comment]
I will review soon

**Comment by Ckbhatia** [comment]
Your PR is in review now. I will update you soon.

**Comment by Ckbhatia** [comment]
Hi @mihirgupta0900, I have review your commits. It is working fine for me.

Can you please run this git command and push changes: `git pull --rebase <this project> feature`

You need to pull, merge/rebase and push the latest changes from the feature branch. So, I can merge your master branch.

**Comment by mihirgupta0900** [comment]
Done!

**Pull request merged**
