### PR TITLE
Implement filter articles by topics

### PR DESCRIPTION
**Pull request by marcotgs**
#11

### CODE REVIEW

**Comment by Ckbhatia** [comment]
There's window property error as it isn't available in build time.

Can you fix this error and deploy it for review?

image

**Comment by Ckbhatia** [comment]
I have deployed your PR and review it. Your work must be appreciated.

There are some changes needed for UI as it it looking broken.

Can you improve that?

**Comment by marcotgs** [comment]
Do you mean looking broken on mobile?

Could you give some examples about what could be improved?

**Comment by Ckbhatia** [comment]
Okay, I will give you mockup.

**Comment by Ckbhatia** [comment]
Search results should appear like this:

Desktop:
Desktop

Or else show box same as before in desktop view.


Mobile: ( pretty much same as already there )
mobile

**Comment by Ckbhatia** [comment]
Awesome job 👍

Can you raise this PR against the feature branch? I will merge it.

**Comment by marcotgs** [comment]
I changed the base to `feature` branch.

**Pull request merged**
